name: jessicabrentnall Deploy to CO.UK

permissions:
  contents: read

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Set up Ruby 3.2.x
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true

    - name: Install Packages
      run: |
        npm run install-jekyll

    - name: Build Jekyll
      working-directory: ./site
      run: |
        bundle exec jekyll build


    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
        aws-region: eu-west-2

    - name: Deploy To S3
      run: |
        aws s3 sync ./site/_site/ s3://jessicabrentnall.co.uk/  --delete
        echo "Deployed to S3"

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id EC8POOU1IP5LQ --paths "/*"
        echo 'Invalidated CloudFront cache'
