name: JessWhite Deploy to CO.UK

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 3.1.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x

    - name: Install Packages
      run: |
        npm run install-jekyll

    - name: Build Jekyll
      working-directory: ./site
      run: |
        bundle exec jekyll build